### ISSUE TITLE
SSL handshake

### ISSUE THREAD

**Issue by pwalczysko** [ome/ansible-example-omero-onenode#14]
When using local CLI connecting to an OMERO.server installed inside a docker using the playbook from this repo, the connection of the CLI is successful, but an import attempt ends in SSL handshake error. 

The docker provisioning and OMERO.install see https://github.com/ome/ansible-example-omero-onenode/issues/13

The error on import is

<details>

```
(cli) pwalczysko@ls31618~$ omero import -T Dataset:name:test1 ~/Desktop/Iviewer0c.png 
Using OMERO.java-5.6.3-ice36-b228
Using session for root@localhost:4064. Idle timeout: 10 min. Current group: system
2022-08-26 10:45:33,154 322        [      main] INFO          ome.formats.importer.ImportConfig - OMERO.blitz Version: 5.5.8
2022-08-26 10:45:33,181 349        [      main] INFO          ome.formats.importer.ImportConfig - Bioformats version: 6.5.1 revision: 6f50e4d52c9d96112635fd8b2dde737f31041cf0 date: 7 July 2020
2022-08-26 10:45:33,262 430        [      main] INFO   formats.importer.cli.CommandLineImporter - Log levels -- Bio-Formats: ERROR OMERO.importer: INFO
2022-08-26 10:45:33,865 1033       [      main] INFO      ome.formats.importer.ImportCandidates - Depth: 4 Metadata Level: MINIMUM
2022-08-26 10:45:33,968 1136       [      main] INFO      ome.formats.importer.ImportCandidates - 1 file(s) parsed into 1 group(s) with 1 call(s) to setId in 99ms. (102ms total) [0 unknowns]
2022-08-26 10:45:34,031 1199       [      main] INFO       ome.formats.OMEROMetadataStoreClient - Attempting initial SSL connection to localhost:4064
2022-08-26 10:45:34,786 1954       [      main] ERROR  formats.importer.cli.CommandLineImporter - Error during import process.
Ice.SecurityException: javax.net.ssl.SSLHandshakeException: The server selected protocol version TLS10 is not accepted by client preferences [TLS12]
	at IceInternal.AsyncResultI.__wait(AsyncResultI.java:276) ~[ice.jar:na]
	at Ice.ObjectPrxHelperBase.end_ice_isA(ObjectPrxHelperBase.java:310) ~[ice.jar:na]
	at Ice.ObjectPrxHelperBase.ice_isA(ObjectPrxHelperBase.java:92) ~[ice.jar:na]
	at Ice.ObjectPrxHelperBase.ice_isA(ObjectPrxHelperBase.java:69) ~[ice.jar:na]
	at Ice.ObjectPrxHelperBase.checkedCastImpl(ObjectPrxHelperBase.java:2810) ~[ice.jar:na]
	at Ice.ObjectPrxHelperBase.checkedCastImpl(ObjectPrxHelperBase.java:2770) ~[ice.jar:na]
	at Glacier2.RouterPrxHelper.checkedCast(RouterPrxHelper.java:1787) ~[glacier2.jar:na]
	at omero.client.getRouter(client.java:889) ~[omero-blitz.jar:5.5.8]
	at omero.client.createSession(client.java:810) ~[omero-blitz.jar:5.5.8]
	at omero.client.joinSession(client.java:745) ~[omero-blitz.jar:5.5.8]
	at ome.formats.OMEROMetadataStoreClient.initialize(OMEROMetadataStoreClient.java:764) ~[omero-blitz.jar:5.5.8]
	at ome.formats.importer.ImportConfig.createStore(ImportConfig.java:381) ~[omero-blitz.jar:5.5.8]
	at ome.formats.importer.cli.CommandLineImporter.<init>(CommandLineImporter.java:162) ~[omero-blitz.jar:5.5.8]
	at ome.formats.importer.cli.CommandLineImporter.main(CommandLineImporter.java:997) ~[omero-blitz.jar:5.5.8]
Caused by: javax.net.ssl.SSLHandshakeException: The server selected protocol version TLS10 is not accepted by client preferences [TLS12]
	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[na:1.8.0_333]
	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[na:1.8.0_333]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:357) ~[na:1.8.0_333]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:313) ~[na:1.8.0_333]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:304) ~[na:1.8.0_333]
	at sun.security.ssl.ServerHello$ServerHelloConsumer.onServerHello(ServerHello.java:941) ~[na:1.8.0_333]
	at sun.security.ssl.ServerHello$ServerHelloConsumer.consume(ServerHello.java:868) ~[na:1.8.0_333]
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:376) ~[na:1.8.0_333]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:479) ~[na:1.8.0_333]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:990) ~[na:1.8.0_333]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:977) ~[na:1.8.0_333]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_333]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:924) ~[na:1.8.0_333]
	at IceSSL.TransceiverI.handshakeNonBlocking(TransceiverI.java:363) ~[ice.jar:na]
	at IceSSL.TransceiverI.initialize(TransceiverI.java:33) ~[ice.jar:na]
	at Ice.ConnectionI.initialize(ConnectionI.java:1921) ~[ice.jar:na]
	at Ice.ConnectionI.message(ConnectionI.java:940) ~[ice.jar:na]
	at IceInternal.ThreadPool.run(ThreadPool.java:395) ~[ice.jar:na]
	at IceInternal.ThreadPool.access$300(ThreadPool.java:12) ~[ice.jar:na]
	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:832) ~[ice.jar:na]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_333]
```

</details>

cc @jburel @sbesson

**Comment by pwalczysko** [comment]
Thank you @sbesson , the first testing (rerunning of the playbook on the existing docker with that line included ) fixed the problem. I will try to create a more acceptable setup (not mentioning "Debian"), run on a fresh docker and come up with a PR.
